SUPPORTS_NATIVE_GOOGLE_CAMERA := YES
SUPPORTS_GOOGLE_WALLS := YES
SUPPORTS_GOOGLE_NEW_ASSISTANT := NO
SUPPORTS_GOOGLE_ASSISTANT_EXTRA_RESOURCES := NO
SUPPORTS_PIXEL_SETUP_OVERLAYS := YES
PIXEL_SETUP_OVERLAY_TYPE := PIXELTWOTHREE
TARGET_INCLUDE_STOCK_ARCORE := YES
